# Generated by Django 6.0 on 2025-12-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = []
