# Generated by Django 6.0 on 2025-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_fix_user_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="rows_added",
            field=models.IntegerField(default=0),
        ),
    ]
